num1 = int(input("num1 = "))
num2 = int(input("num2 = "))
print("Sum =",num1 + num2)
print("Difference =",num1 - num2)
print("Product = ",num1 * num2)
print("Division = ",num1 / num2)
print("Floor Division = ",num1 // num2)
print("Modulus =",num1 %num2)
print("Power = ",num1 ** num2)