Name = input("Enter the Name = ")
Roll_number = int(input("Enter the Roll number = "))
Branch = input("Enter the Branch = ")
Semester = input("Enter the SEmester = ")
CGPA = float(input("Enter the CGPA  = "))
College = input("Enter the college = ")
Mobile_number = int(input("Enter the mobile number = "))
print("Student Profile\n")
print("Name = ",Name)
print("Roll_number = ",Roll_number)
print("Branch = ",Branch)
print("Semester = ",Semester)
print("CGPA = ",CGPA)
print("College = ",College)
print("Mobile number = ",Mobile_number)